# Local development overrides

url: http://localhost:4000
baseurl: ""

# Disable heavy optimizations for easier debugging
minify: false
remove_HTML_comments: false

# Optional: silence external analytics while developing
google_analytics: 
panelbear_analytics: 
bing_site_verification: 
google_site_verification: 

